#!/bin/sh
noass=${1-0}
nostop=${2-0}
qsettings='-keyint_min 5 -g 15'
osize='320x180'
input=input.mov
output=test.mp4
m4v=test.m4v
if [ ! -z "$1" -a "$1" = '-h' -o "$1" = '-help' ] ; then
    echo "regress [noass=1] [nostop=1]"
    exit 0
fi
echo "Checking ffmpeg"
#libvo_aacenc
target/bin/ffmpeg -y -i "$input" -loglevel verbose -threads 2 -acodec libfaac -ar 48000 -ab 192k -vcodec libx264 -coder 0 $qsettings \
    -qmin 10 -qmax 51 -sc_threshold 40 -qdiff 4 -i_qfactor 0.71 -qblur .5 -me_range 4 -me_method dia -subq 1 -refs 2 -b_strategy 1 -bf 16 \
    -flags +loop -b:v 400k -bt 300k -r 30 -s $osize -strict -2 -map_chapters -1 -map_metadata -1 -rc_eq 'blurCplx^(1-qComp)' \
    "$output" 2>&1 | tee test.log
err=$?
if [ $err -ne 0 ] ; then
    echo "ffmpeg FAIL: $input ($err)"
    exit $err
fi
target/bin/ffprobe $output 2>&1 | tee -a test.log
err=$?
if [ $err -ne 0 ] ; then
    echo "ffprobe FAIL: $output ($err)"
fi
egrep 'Duration|Stream' test.log > test.out
diff -q ref.out test.out
err=$?
if [ $err -ne 0 ] ; then
    echo "regression FAIL: `diff ref.out test.out`"
    [ $nostop -eq 0 ] && exit $err
fi
echo "ffmpeg SUCCESS"
if [ $noass = '0' ] ; then
    echo "checking ffmpeg embed"
    target/bin/ffmpeg -y -i $output -vf subtitles=input.srt $m4v 2> /dev/null
    err=$?
    if [ $err -ne 0 ] ; then
	echo "ffmpeg embed srt FAIL: ($err)"
	[ $nostop -eq 0 ] && exit $err
    fi
    echo "ffmpeg embed srt SUCCESS"
    echo "checking ffmpeg embed red"
    target/bin/ffmpeg -y -i input.srt test.ass 2> /dev/null
    err=$?
    if [ $err -ne 0 ] ; then
	echo "ffmpeg embed red srt FAIL: ($err)"
	[ $nostop -eq 0 ] && exit $err
    fi
    cat test.ass | sed 's/,[0-9][0-9],\&Hffffff,/,20,\&Hff00ff,/' > $$.ass
    mv $$.ass test.ass
    target/bin/ffmpeg -y -i $output -vf subtitles=test.ass $m4v 2> /dev/null
    if [ $err -ne 0 ] ; then
	echo "ffmpeg embed red srt FAIL: ($err)"
	[ $nostop -eq 0 ] && exit $err
    fi
    echo "ffmpeg embed red srt SUCCESS"
fi
echo "checking libs"
if [ `uname` = 'Darwin' ] ; then
    otool -L target/bin/ffmpeg | awk '{print $1}' | sort | grep -v ffmpeg: | tee test.libs
    ref=osx_ref.libs
else
    ldd target/bin/ffmpeg | awk '{print $1}' | sort | tee test.libs
    ref=linux_ref.libs
fi
diff -q $ref test.libs
err=$?
if [ $err -ne 0 ] ; then
    diff $ref test.libs | egrep -q '^<'
    err=$?
    if [ $err -ne 0 ] ; then
	echo "libs FAILURE: `diff $ref test.libs`"
    else
	echo "libs WARNING: `diff $ref test.libs`"
    fi
    exit $err
fi
echo "libs SUCCESS"
exit 0
